language: minimal
services:
- docker
before_install:
- docker pull dm874/deploy
stages:
- build-publish
- deploy
jobs:
  include:
  - stage: build-publish
    script: docker build -t router . && sh deployment/publish_router.sh
  - stage: deploy
    script: sh deployment/deploy_router.sh
env:
  global:
  - secure: K/hh6QCVlvv3WQ48NaLs1mcD2IYZB6nbt6wert7VNqhIi+Pd4SAlKHFzTwpi75+IKUeLx9QVs/iUWlgwBOKkJp+aRMbVyeMkXTctQ20z7UMBdTtv7TD6BaMO6gLgdxxT77JXQmsfY3VFH/Wn6NQ0qpXPLj7JEPKVqLIyW/PrWjyQYaw+9+vz9KzmPxyDGTIMS8z/mhdylvCtkT4AxVsoQXLC3rCj4j6TGjlC1I8msRRr6fgIdzGABxO10le5bld/8PSadhB/Z4m8pagqo4JDYMFPetSNB4WPLp0L1AvegIOY9bbyhhxFFKohiTzP1uMVg28oxyGu5ytWyUYUkKsjw+cCHC6yguNXZhtriRLFwkOeYW/IfVEq/1llWic4pciL0En+ddemZKDAd5L1EpMaAeJt6RJThjB8YaaFV6sXnFnTxh0o7TT4AAP+kO2Tuiq/fL/P3CaAt+xfZKTd4oE4h8s49n95OWMLG+Z6bHu9bT8FZy+cv8uUrwwtfJ1avNyvcXYYEqCT8vN9CxtzUuSvizCmj1/oYAAMa7BId79QOqAeR9buoDZBYRrUP6YCCNohrPm5U3qMLR1M67pl0WikPcsgnbuzdKG3hTKATE7Gw97zkNxTJcti64hTpnuDmE6baLtJ7MPTxH6W6dAvNnkzkrfaLqUMPxba1SBQEFgQ+Ts=
  - secure: e0d0mG8bGDVlRiKdcRTVAaUtHF/f6iJ7YK1gW7K7HbCQlHEuVURVwSxusGtJkxyUddzpqUmn1ZCc96WLwBjijv1EX6yEpYWG7k5PZpqlVzsWkt91rKbZstzeFbsRCTtQrSJ9i4JcThM4DS5AoRDdB/WKZPooezwxPek1Y3gAsCv4rddRAl7yL0mf0rIOz7wxorY16cO3w72lpc+DHYP+uDd52fz1wvUsoS7+blxLNs3T5XrAIbLdJ2VxRNf41lnCrlw5R6K0l174n0euG7U6RArDbnHYnmSTGsJ08EJay3uJewtqNx5ILIkWzkNMhuYh8Y+D1ngHvSDd8i5eFlYIcMTRX3GZfMuWwomljAlWrdnw3hxPOuThJlEtvB5kRuAUk4yJDHZGF6Ca0sVnnngZGhmWEzGuPcdsuelmP8ZlezqfWOiHRSqon11AIbJ3DqreIusdQC8m6rqpgVqj02JDBFJMqxx9NpxSOfO/dqRvy7s580JReDQbszgFW2WpJI5ZBZ9d5KSUG3yEeaq42lwCfNq9BSwjO3YlXFpTa+WDhZoC23byGoG8z7PgMGOIUZk7sLwqo2Ry7VizC3WTjLRWdku7IimqYWjcKbLyzrbo5mokAoPqS7hjp4Pl6/9MDQj63xNnGEmf0zhvC3HlTeFIPAYI4ZYYwYbBVgGxBkWAczU=
  - secure: aujH+i4ymARMWjwp+ejB7WZMGqkakxIqeiS/BaB8R2f0l7L6Ed04oQ0yWjobc/P1NELGII6XTKPa55v8F9QsxvhSGg3CjDfNcYSKIrSYAdV6b496sY89w8SWNcFy0gvwIJJ6LIQAn5KS6BoqaV/iJzwr8CoHL4mBlrZta40eh18qGieSz7pEvSCWM/LT0aDyiyrJNENyDj48Yubs444iEAjYap5HI7rSfrbfg9xf+0eiZO4ZVpbItklub+Fz1LERH7rCJm9Gl7gk3K2Y0dkz1E1N8Mk+pHJUjoPMCHNTiHiw5vYbQp6cDSZEzJFpJ8nQU4p8I9PYPbAA9THTLit+a1tCTMpbmvqjxn6Kf17EoZFhqkAX1qeo4oj12E5t7RmI/kM6kfj3nz2AjX8EJU9bUAaBTZMV/LmJq+kk/juSGlW1YDyvKpc+PCJnAODAZO+rq73KjSYJafTKMcSZQKbhD7wRonAOLJ4rUbSFnxS71xlwvaeAZNVBhjS7zvicpOoClLJHYDXJ5+y3zsUthK21jFLZzK+OMq/Yc9ZQifWkluRudne2sQJzleTrx9EL9nvi5xkf5KisG9IQ32C+/N17ebf6yQgWNydx/YwAdxJZ0wRL852Dmf4ia3fZBSOFvGdQVx6tuhYLGqKyZE0+K0/tqR9t2A07XYQv/kzABDWGiAw=
